spring.application.name=classic

app.url=${url}

app.db.location=${db_url}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
#hide this in git
spring.mail.password=


# Fix for STARTTLS Error
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
